title: Logic and Bounded Rationality 2026
description: Online workshop · 25–27 February 2026 · Microsoft Teams
theme: just-the-docs

url: logic-bounded-rationality-2026

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
